version: '3.8'
services:

  finalapi:
    image: finalapi:v1
    hostname: api.authsamples-dev.com
    ports:
      - 445:8000
    volumes:
      - ../environments/dockercompose.config.json:/usr/api/api.config.json
      - ./trusted.ca.pem:/usr/local/share/ca-certificates/trusted.ca.crt
      - ../certs/authsamples-dev.ssl.p12:/usr/api/certs/authsamples-dev.ssl.p12
    environment:
      NODE_EXTRA_CA_CERTS: '/usr/local/share/ca-certificates/trusted.ca.crt'
