#
# The Kubernetes deployment file for our NodeJS API
# API instances run on dynamically assigned IP addresses and a low privilege port
# API instances cannot be called directly from outside Kubernetes
#

kind: Service
apiVersion: v1
metadata:
  name: nodeapi-svc
spec:
  selector:
    app: nodeapi
  ports:
  - protocol: "TCP"
    port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi
  labels:
    app: nodeapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapi
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      containers:
      - name: nodeapi
        image: nodeapi:v1
        imagePullPolicy: Never
      
      # If required the API pod can add custom host file entries, eg for Ingress URLs
      # This might enable a Kubernetes API to call a development authorization server over SSL
      hostAliases:
      - ip: 192.168.64.3
        hostnames:
        - login.mycompany.com